// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgDTu_auHyOaikvk4C21tif02dUDEsFGM',
    appId: '1:1016512603053:web:0a25871404553862e4b724',
    messagingSenderId: '1016512603053',
    projectId: 'abgram',
    authDomain: 'abgram.firebaseapp.com',
    storageBucket: 'abgram.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9oq2ksicLJUuy9mle7TyKhXoz9XA5VtI',
    appId: '1:1016512603053:android:4249c88990b353ade4b724',
    messagingSenderId: '1016512603053',
    projectId: 'abgram',
    storageBucket: 'abgram.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuFhrAtUNSPcSthb8E_n3-85LmXNa-xxw',
    appId: '1:1016512603053:ios:153b847bc8530d42e4b724',
    messagingSenderId: '1016512603053',
    projectId: 'abgram',
    storageBucket: 'abgram.appspot.com',
    androidClientId: '1016512603053-9euf5ir93ef3sfj8tlqmobu24ipm09lv.apps.googleusercontent.com',
    iosClientId: '1016512603053-0epmhci1ocnnrenpdv6909pdqhrfgr3m.apps.googleusercontent.com',
    iosBundleId: 'com.ab.abgram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuFhrAtUNSPcSthb8E_n3-85LmXNa-xxw',
    appId: '1:1016512603053:ios:153b847bc8530d42e4b724',
    messagingSenderId: '1016512603053',
    projectId: 'abgram',
    storageBucket: 'abgram.appspot.com',
    androidClientId: '1016512603053-9euf5ir93ef3sfj8tlqmobu24ipm09lv.apps.googleusercontent.com',
    iosClientId: '1016512603053-0epmhci1ocnnrenpdv6909pdqhrfgr3m.apps.googleusercontent.com',
    iosBundleId: 'com.ab.abgram',
  );
}
